package com.example.thesisbe.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
@Entity
public class UserProfile {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String email;
    private String educationLevel;
    private String interests;
    private String skills;

    @Column(length = 500)
    private String careerGoals;

    // Getters and setters generated by Lombok
}